import { useState } from 'react'
import type { Lang } from '../types'
import { LegalPage } from './Privacy'

const CONTENT: Record<Lang, { title: string; subtitle: string; updated: string; sections: { heading: string; body: string }[] }> = {
  en: {
    title: 'HIPAA Notice of Privacy Practices',
    subtitle: 'This notice describes how medical information about you may be used and disclosed and how you can get access to this information.',
    updated: 'Effective Date: April 24, 2026 | Last Revised: April 24, 2026',
    sections: [
      { heading: 'PLEASE REVIEW THIS NOTICE CAREFULLY', body: 'This Notice of Privacy Practices describes how PatientTrac Corp and the healthcare providers using our platform may use and disclose your Protected Health Information (PHI) to carry out treatment, payment, or healthcare operations and for other purposes permitted or required by law. It also describes your rights to access and control your PHI.' },
      { heading: 'What is Protected Health Information (PHI)?', body: 'PHI is information about you, including demographic information, that may identify you and that relates to your past, present, or future physical or mental health condition, the provision of healthcare services to you, or the past, present, or future payment for the provision of healthcare services to you. PHI includes, but is not limited to: your name, address, date of birth, Social Security number, insurance information, diagnoses, medications, lab results, and treatment records.' },
      { heading: 'How We May Use and Disclose Your PHI', body: 'TREATMENT: We may use and disclose your PHI to provide, coordinate, or manage your healthcare and related services. This includes sharing information with other healthcare providers involved in your care.\n\nPAYMENT: We may use and disclose your PHI to obtain payment for healthcare services provided to you. This includes submitting claims to insurance companies and coordinating benefits.\n\nHEALTHCARE OPERATIONS: We may use and disclose your PHI for healthcare operations, including quality assessment, employee training, business planning, and legal services.\n\nAPPOINTMENT REMINDERS: We may contact you to provide appointment reminders or information about treatment alternatives.\n\nBUSINESS ASSOCIATES: We may disclose your PHI to our business associates (such as technology vendors) who perform services on our behalf. All business associates are required to protect your PHI under a Business Associate Agreement.\n\nAS REQUIRED BY LAW: We will disclose your PHI when required by federal, state, or local law, including to public health authorities, law enforcement, or in response to court orders.' },
      { heading: 'Uses and Disclosures Requiring Your Authorization', body: 'For uses and disclosures beyond those described above, we will ask for your written authorization. This includes: (a) marketing communications; (b) sale of your PHI; (c) most uses and disclosures of psychotherapy notes; (d) disclosures for research purposes (except where a waiver has been granted by an IRB); (e) disclosures to your employer. You may revoke your authorization at any time in writing.' },
      { heading: 'Your Rights Regarding Your PHI', body: 'RIGHT TO ACCESS: You have the right to inspect and obtain a copy of your PHI maintained in your medical record. We will provide access within 30 days of your request.\n\nRIGHT TO AMEND: You have the right to request amendments to your PHI if you believe it is incorrect or incomplete. We may deny your request under certain circumstances.\n\nRIGHT TO AN ACCOUNTING: You have the right to request a list of disclosures of your PHI made for purposes other than treatment, payment, or operations.\n\nRIGHT TO RESTRICT: You have the right to request restrictions on certain uses and disclosures of your PHI. We are not required to agree to your request unless it involves disclosures to a health plan for services you have paid for in full.\n\nRIGHT TO CONFIDENTIAL COMMUNICATIONS: You have the right to request that we communicate with you about your PHI by alternative means or at alternative locations.\n\nRIGHT TO A PAPER COPY: You have the right to obtain a paper copy of this Notice upon request, even if you have agreed to receive this notice electronically.\n\nRIGHT TO BREACH NOTIFICATION: You have the right to be notified in the event of a breach of your unsecured PHI.' },
      { heading: 'Our Duties', body: 'PatientTrac Corp and the covered entities using our platform are required by law to: (a) maintain the privacy of your PHI; (b) provide you with this Notice of our legal duties and privacy practices; (c) notify you following a breach of your unsecured PHI; (d) abide by the terms of the Notice currently in effect. We reserve the right to change our privacy practices and the terms of this Notice. If we make a material change, we will notify affected patients via email.' },
      { heading: 'Security Safeguards', body: 'We implement the following administrative, physical, and technical safeguards to protect your PHI:\n\nADMINISTRATIVE: Staff training on HIPAA compliance; privacy officer designation; access control policies; regular risk assessments; incident response procedures.\n\nPHYSICAL: Secure data center facilities (Supabase/AWS us-east-1); access restrictions to physical infrastructure; workstation security controls.\n\nTECHNICAL: AES-256 encryption at rest; TLS 1.3 encryption in transit; role-based access control (RBAC); multi-factor authentication (MFA) for all staff; audit logging of all PHI access events; automatic session timeouts.' },
      { heading: 'Data Breach Notification', body: 'In the event of a breach of unsecured PHI, we will notify you without unreasonable delay and within 60 days of discovery of the breach, as required by the HIPAA Breach Notification Rule. Notification will include: description of the breach; types of PHI involved; steps you should take to protect yourself; what we are doing to investigate, mitigate, and prevent future breaches; contact information for questions.' },
      { heading: 'Business Associates', body: 'PatientTrac Corp serves as a Business Associate to covered healthcare entities using our platform. We have signed Business Associate Agreements (BAAs) with all covered entities. Our key technology subprocessors include:\n\n• Supabase (database hosting, us-east-1 region, SOC 2 Type II certified)\n• Netlify (web hosting and CDN)\n• HubSpot (CRM — non-PHI contact data only)\n• Stripe (payment processing — financial data only, no PHI)\n\nAll subprocessors operate under contractual obligations to protect your data.' },
      { heading: 'Complaints', body: 'If you believe your privacy rights have been violated, you may file a complaint with:\n\n1. PatientTrac Corp Privacy Office:\n   Email: privacy@patienttrac.com\n   We will not retaliate against you for filing a complaint.\n\n2. U.S. Department of Health and Human Services — Office for Civil Rights:\n   Website: www.hhs.gov/ocr/privacy/hipaa/complaints\n   Phone: 1-800-368-1019\n   TTY: 1-800-537-7697' },
      { heading: 'Contact Information', body: 'For questions about this Notice or your privacy rights:\n\nPatientTrac Corp — Privacy Officer\nEmail: privacy@patienttrac.com\nGeneral Support: support@patienttrac.com\nPhone: Contact via email for fastest response\nAddress: PatientTrac Corp, Miami, FL, USA\n\nThis Notice is effective as of the date shown above and applies to all PHI collected through the PatientTrac Patient Profiler platform.' },
    ],
  },
  es: {
    title: 'Aviso de Prácticas de Privacidad HIPAA',
    subtitle: 'Este aviso describe cómo se puede usar y divulgar su información médica y cómo puede acceder a ella.',
    updated: 'Fecha de vigencia: 24 de abril de 2026',
    sections: [
      { heading: 'POR FAVOR LEA ESTE AVISO CUIDADOSAMENTE', body: 'Este Aviso de Prácticas de Privacidad describe cómo PatientTrac Corp y los proveedores de atención médica que usan nuestra plataforma pueden usar y divulgar su Información de Salud Protegida (PHI) para llevar a cabo tratamientos, pagos u operaciones de atención médica.' },
      { heading: '¿Qué es la Información de Salud Protegida (PHI)?', body: 'La PHI es información sobre usted que puede identificarle y que se relaciona con su condición de salud física o mental pasada, presente o futura, la prestación de servicios de atención médica, o el pago por esos servicios. Incluye: nombre, dirección, fecha de nacimiento, número de seguro social, información del seguro médico, diagnósticos, medicamentos y registros de tratamiento.' },
      { heading: 'Cómo Podemos Usar y Divulgar su PHI', body: 'TRATAMIENTO: Podemos usar y divulgar su PHI para proporcionar, coordinar o gestionar su atención médica.\n\nPAGO: Podemos usar su PHI para obtener el pago por los servicios de atención médica.\n\nOPERACIONES DE ATENCIÓN MÉDICA: Podemos usar su PHI para operaciones como evaluación de calidad y capacitación de empleados.\n\nASEGURACIÓN SEGÚN REQUERIDO POR LA LEY: Divulgaremos su PHI cuando lo requieran las leyes federales, estatales o locales.' },
      { heading: 'Sus Derechos Respecto a su PHI', body: 'DERECHO DE ACCESO: Tiene derecho a inspeccionar y obtener una copia de su PHI dentro de los 30 días de su solicitud.\n\nDERECHO A ENMENDAR: Tiene derecho a solicitar enmiendas a su PHI si cree que es incorrecta.\n\nDERECHO A RESTRICCIONES: Tiene derecho a solicitar restricciones sobre ciertos usos de su PHI.\n\nDERECHO A NOTIFICACIÓN DE VIOLACIÓN: Tiene derecho a ser notificado en caso de una violación de su PHI no asegurada.' },
      { heading: 'Nuestros Deberes', body: 'PatientTrac Corp está legalmente obligada a: (a) mantener la privacidad de su PHI; (b) proporcionarle este Aviso; (c) notificarle después de una violación de su PHI no asegurada; (d) cumplir con los términos de este Aviso.' },
      { heading: 'Medidas de Seguridad', body: 'Implementamos las siguientes salvaguardas para proteger su PHI:\n\nADMINISTRATIVAS: Capacitación del personal en cumplimiento de HIPAA; designación de oficial de privacidad; evaluaciones de riesgo regulares.\n\nTÉCNICAS: Encriptación AES-256 en reposo; TLS 1.3 en tránsito; control de acceso basado en roles; autenticación multifactor; registro de auditoría de todos los accesos a PHI.' },
      { heading: 'Notificación de Violación de Datos', body: 'En caso de una violación de PHI no asegurada, le notificaremos sin demora injustificada y dentro de los 60 días de descubrimiento, según lo requiere la Regla de Notificación de Violaciones de HIPAA.' },
      { heading: 'Asociados Comerciales', body: 'PatientTrac Corp sirve como Asociado Comercial de entidades cubiertas. Hemos firmado Acuerdos de Asociados Comerciales (BAA) con todas las entidades cubiertas. Nuestros subprocesadores tecnológicos incluyen Supabase, Netlify, HubSpot (solo datos de contacto no PHI) y Stripe (solo datos financieros).' },
      { heading: 'Quejas', body: 'Si cree que sus derechos de privacidad han sido violados, puede presentar una queja con:\n\n1. Oficina de Privacidad de PatientTrac Corp:\n   Correo: privacy@patienttrac.com\n\n2. Departamento de Salud y Servicios Humanos de EE.UU. — Oficina de Derechos Civiles:\n   Sitio web: www.hhs.gov/ocr/privacy/hipaa/complaints\n   Teléfono: 1-800-368-1019' },
      { heading: 'Información de Contacto', body: 'Para preguntas sobre este Aviso:\n\nPatientTrac Corp — Oficial de Privacidad\nCorreo: privacy@patienttrac.com\nSoporte: support@patienttrac.com' },
    ],
  },
  fr: {
    title: 'Avis de Pratiques de Confidentialité HIPAA',
    subtitle: 'Cet avis décrit comment vos informations médicales peuvent être utilisées et divulguées et comment vous pouvez y accéder.',
    updated: 'Date d\'entrée en vigueur: 24 avril 2026',
    sections: [
      { heading: 'VEUILLEZ LIRE CET AVIS ATTENTIVEMENT', body: 'Cet Avis de Pratiques de Confidentialité décrit comment PatientTrac Corp et les prestataires de soins utilisant notre plateforme peuvent utiliser et divulguer vos Informations de Santé Protégées (PHI) pour effectuer des traitements, des paiements ou des opérations de soins de santé.' },
      { heading: 'Qu\'est-ce que l\'Information de Santé Protégée (PHI)?', body: 'Les PHI sont des informations vous concernant qui peuvent vous identifier et qui se rapportent à votre état de santé physique ou mentale passé, présent ou futur, la prestation de services de soins de santé ou le paiement de ces services. Elles incluent: nom, adresse, date de naissance, numéro de sécurité sociale, informations d\'assurance, diagnostics, médicaments et dossiers de traitement.' },
      { heading: 'Comment Nous Pouvons Utiliser et Divulguer Vos PHI', body: 'TRAITEMENT: Nous pouvons utiliser et divulguer vos PHI pour fournir, coordonner ou gérer vos soins de santé.\n\nPAIEMENT: Nous pouvons utiliser vos PHI pour obtenir le paiement des services de soins de santé.\n\nOPÉRATIONS: Nous pouvons utiliser vos PHI pour des opérations telles que l\'évaluation de la qualité et la formation.\n\nCONFORMÉMENT À LA LOI: Nous divulguerons vos PHI lorsque requis par les lois fédérales, étatiques ou locales.' },
      { heading: 'Vos Droits Concernant Vos PHI', body: 'DROIT D\'ACCÈS: Vous avez le droit d\'inspecter et d\'obtenir une copie de vos PHI dans les 30 jours suivant votre demande.\n\nDROIT D\'AMENDEMENT: Vous avez le droit de demander des modifications à vos PHI si vous pensez qu\'elles sont incorrectes.\n\nDROIT À LA NOTIFICATION DE VIOLATION: Vous avez le droit d\'être notifié en cas de violation de vos PHI non sécurisées.' },
      { heading: 'Nos Obligations', body: 'PatientTrac Corp est légalement tenue de: (a) maintenir la confidentialité de vos PHI; (b) vous fournir cet Avis; (c) vous notifier après une violation de vos PHI non sécurisées; (d) respecter les termes de cet Avis.' },
      { heading: 'Mesures de Sécurité', body: 'Nous mettons en œuvre les protections suivantes:\n\nADMINISTRATIVES: Formation du personnel sur la conformité HIPAA; désignation d\'un responsable de la confidentialité; évaluations régulières des risques.\n\nTECHNIQUES: Chiffrement AES-256 au repos; TLS 1.3 en transit; contrôle d\'accès basé sur les rôles; authentification multifacteur; journalisation des audits.' },
      { heading: 'Notification de Violation de Données', body: 'En cas de violation de PHI non sécurisées, nous vous notifierons sans délai injustifié et dans les 60 jours suivant la découverte, conformément à la Règle de Notification de Violation de HIPAA.' },
      { heading: 'Associés Commerciaux', body: 'PatientTrac Corp agit en tant qu\'Associé Commercial d\'entités de soins couvertes. Nous avons signé des Accords d\'Associés Commerciaux (BAA) avec toutes les entités couvertes. Nos sous-traitants technologiques incluent Supabase, Netlify, HubSpot (données de contact non-PHI uniquement) et Stripe (données financières uniquement).' },
      { heading: 'Plaintes', body: 'Si vous pensez que vos droits à la confidentialité ont été violés:\n\n1. Bureau de la Confidentialité de PatientTrac Corp:\n   Email: privacy@patienttrac.com\n\n2. Département américain de la Santé et des Services sociaux — Bureau des Droits civils:\n   Site web: www.hhs.gov/ocr/privacy/hipaa/complaints\n   Téléphone: 1-800-368-1019' },
      { heading: 'Coordonnées', body: 'Pour toute question concernant cet Avis:\n\nPatientTrac Corp — Responsable de la Confidentialité\nEmail: privacy@patienttrac.com\nSupport: support@patienttrac.com' },
    ],
  },
}

export default function Hipaa() {
  const [lang, setLang] = useState<Lang>(() => {
    const nav = navigator.language?.slice(0, 2)
    if (nav === 'es') return 'es'
    if (nav === 'fr') return 'fr'
    return 'en'
  })
  return <LegalPage lang={lang} setLang={setLang} content={CONTENT[lang]} color="#4ade80" badge="HIPAA NOTICE" />
}
